### PR TITLE
Fix flakey / faulty tests for dev / preview

### PR DESCRIPTION
**Pull request by benthorner**
https://www.pivotaltracker.com/n/projects/1443052/stories/176742683

Please see the commits for more details.

### CODE REVIEW

**Comment by benthorner** [comment]
Converting to "draft" as there's a discrepancy depending on whether these are run locally on or CI.

**Comment by CrystalPea** [comment]
Hey, what do you mean by `log entry` in this context? I don't understand this and consequently do not understand this PR 😅

**Comment by tombye** [comment]
I'm pretty sure `log_entry` refers to an entry in the 'Message log' list on `/services/<service_id>/api`. Ben has fixed some of my test code here so I recognise it 🙂

**Comment by CrystalPea** [comment]
Ahh, sweet, thanks a lot @tombye

**Comment by CrystalPea** [comment]
Ahh, I get it now @benthorner *galaxy_brain_moment*

**Comment by benthorner** [comment]
Thanks for the question @CrystalPea. I assumed "everyone else will know what this is because they're all familiar with Notify" 😅. I had a bit of trouble choosing which words: in the UI it's described as a "message log" (see below), and in the code they're referred to as "notifications" ([here](https://github.com/alphagov/notifications-admin/blob/5bc229222be579ce21db26074f4e983fe9c12e74/app/templates/views/api/index.html#L38)), so I went with something in the middle.

Screenshot 2021-02-04 at 12 56 35

I've amended some of the commits and it's now passing in CI. Think it's ready for a review 👍.

**Comment by benthorner** [comment]
After reviewing this myself, I realised the argument I'm making about the nature of the bug doesn't make sense. Rather than try and amend what's here, I've put up a fresh PR with a new branch/commits, and an explanation that really does match the evidence. See here: https://github.com/alphagov/notifications-functional-tests/pull/370.

**Pull request closed without merging**
